name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test Services
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --prefix ./user-service

      - name: Skip Tests
        run: echo "No tests available. Skipping test step."


  docker-build-and-push:
    name: Build and Push Docker Images to GCR
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Write GCP credentials to file
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > key.json

      - name: Configure Docker to use GCR
        run: |
          gcloud auth activate-service-account --key-file=key.json
          gcloud auth configure-docker --quiet


      - name: Build and Push Gateway Image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/gateway
          docker build -t $IMAGE ./gateway
          docker push $IMAGE

      - name: Build and Push User Service Image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/user-service
          docker build -t $IMAGE ./user-service
          docker push $IMAGE

      - name: Build and Push Course Service Image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/course-service
          docker build -t $IMAGE ./course-service
          docker push $IMAGE

      - name: Build and Push Learner Service Image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/learner-service
          docker build -t $IMAGE ./learner-service
          docker push $IMAGE

      - name: Build and Push Payment Service Image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/payment-service
          docker build -t $IMAGE ./payment-service
          docker push $IMAGE

      - name: Build and Push Notification Service Image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/notification-service
          docker build -t $IMAGE ./notification-service
          docker push $IMAGE

      - name: Build and Push Frontend Image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend
          docker build -t $IMAGE ./frontend
          docker push $IMAGE


  deploy-to-cloudrun:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    needs: docker-build-and-push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy User Service
        run: |
          gcloud run deploy user-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/user-service \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      - name: Deploy Gateway
        run: |
          gcloud run deploy gateway \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/gateway \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      - name: Deploy Course Service
        run: |
          gcloud run deploy course-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/course-service \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      - name: Deploy Learner Service
        run: |
          gcloud run deploy learner-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/learner-service \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      - name: Deploy Payment Service
        run: |
          gcloud run deploy payment-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/payment-service \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      - name: Deploy Notification Service
        run: |
          gcloud run deploy notification-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/notification-service \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      - name: Deploy Frontend
        run: |
          gcloud run deploy frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
