name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test Services
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --prefix ./user-service

      - name: Skip Tests
        run: echo "No tests available. Skipping test step."

  docker-build-and-push:
    name: Build and Push Docker Images to GHCR
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build and Push Gateway Image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/gateway:latest ./gateway
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/gateway:latest

      - name: Build and Push User Service Image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/user-service:latest ./user-service
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/user-service:latest

      - name: Build and Push Course Service Image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/course-service:latest ./course-service
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/course-service:latest

      - name: Build and Push Learner Service Image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/learner-service:latest ./learner-service
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/learner-service:latest

      - name: Build and Push Payment Service Image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/payment-service:latest ./payment-service
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/payment-service:latest

      - name: Build and Push Notification Service Image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/notification-service:latest ./notification-service
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/notification-service:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/frontend:latest ./frontend
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/frontend:latest

  deploy-to-cloudrun:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    needs: docker-build-and-push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy User Service
        run: |
          gcloud run deploy ${{ secrets.GCP_CLOUDRUN_SVC_PREFIX }}user-service \
            --image ghcr.io/${{ secrets.GHCR_USERNAME }}/user-service:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      - name: Deploy Gateway
        run: |
          gcloud run deploy ${{ secrets.GCP_CLOUDRUN_SVC_PREFIX }}gateway \
            --image ghcr.io/${{ secrets.GHCR_USERNAME }}/gateway:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      - name: Deploy Course Service
        run: |
          gcloud run deploy ${{ secrets.GCP_CLOUDRUN_SVC_PREFIX }}course-service \
            --image ghcr.io/${{ secrets.GHCR_USERNAME }}/course-service:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      - name: Deploy Learner Service
        run: |
          gcloud run deploy ${{ secrets.GCP_CLOUDRUN_SVC_PREFIX }}learner-service \
            --image ghcr.io/${{ secrets.GHCR_USERNAME }}/learner-service:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      - name: Deploy Payment Service
        run: |
          gcloud run deploy ${{ secrets.GCP_CLOUDRUN_SVC_PREFIX }}payment-service \
            --image ghcr.io/${{ secrets.GHCR_USERNAME }}/payment-service:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      - name: Deploy Notification Service
        run: |
          gcloud run deploy ${{ secrets.GCP_CLOUDRUN_SVC_PREFIX }}notification-service \
            --image ghcr.io/${{ secrets.GHCR_USERNAME }}/notification-service:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      - name: Deploy Frontend
        run: |
          gcloud run deploy ${{ secrets.GCP_CLOUDRUN_SVC_PREFIX }}frontend \
            --image ghcr.io/${{ secrets.GHCR_USERNAME }}/frontend:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

